# Generated by Django 4.2.18 on 2026-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaul', '0002_alter_passwordentry_site_url_reveallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Password Entries'},
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='category',
            field=models.CharField(choices=[('work', 'Trabajo'), ('personal', 'Personal'), ('social', 'Redes Sociales'), ('finance', 'Finanzas'), ('shopping', 'Compras'), ('entertainment', 'Entretenimiento'), ('education', 'Educación'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
